sudo: required
services:
  - docker

before_install:
  - docker build -t vimalkanagaraj/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true vimalkanagaraj/react-test npm run test

after_success:
  - docker build -t vimalkanagaraj/multi-client ./client
  - docker build -t vimalkanagaraj/multi-nginx ./nginx
  - docker build -t vimalkanagaraj/multi-server ./server
  - docker build -t vimalkanagaraj/multi-worker ./worker
  # Login to the docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push the images to docker hub
  - docker push vimalkanagaraj/multi-client
  - docker push vimalkanagaraj/multi-nginx
  - docker push vimalkanagaraj/multi-server
  - docker push vimalkanagaraj/multi-worker 

